title: Empyr
short_title: Empyr
description: Empyr empowers companies to track and monetize online to offline (o2o) commerce using card linked offers.
include: ['_pages']
permalink: "/:path/"
logo: /assets/logos/empyr.svg
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: false
  posts:
    output: true
  projects:
    output: true
    permalink: "/careers/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
plugins:
  - jekyll-menus
  # - jekyll-feed
  - jekyll-archives
compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true
exclude_from_watch:
  - assets/scss
keywords: Online to Offline, o2o, Card Linked Offers
exclude:
  - package.json
  - package-lock.json
  - gulpfile.js
  - Gemfile.lock
  - maps
  - node_modules
  - assets/scss
  - Gemfile
  - vendor
  - _pages-backup-root




  
# PREVIEW COMMAND
# bundle exec jekyll build --drafts --unpublished --future -d _site

# FORESTRY INSTANT PREVIEW COMMAND
# bundle exec jekyll serve --drafts --unpublished --future --incremental --port 8080 --host 0.0.0.0 -d _site
