title: Empyr
short_title: Empyr
description: Empyr empowers companies to track and monetize online to offline (o2o) commerce using card linked offers.
baseurl: /
url: "https://www.empyr.site"
permalink: "/:path/"
logo: /assets/logos/empyr.svg
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-menus
  # - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
compress_html:
  comments: ["<!-- ", " -->"]
exclude_from_watch:
  - assets/css
keywords: Online to Offline, o2o, Card Linked Offers

# PREVIEW COMMAND
# bundle exec jekyll build --drafts --unpublished --future -d _site

# FORESTRY INSTANT PREVIEW COMMAND
# bundle exec jekyll serve --drafts --unpublished --future --incremental --port 8080 --host 0.0.0.0 -d _site
