---
label: Careers
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: sub_heading
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Sub heading
  description: OPTIONAL
- name: date
  type: datetime
  label: Date Posted
  description: ''
  config:
    required: false
    date_format: MM/DD/YYYY
    time_format: 
    display_utc: false
  default: now
- name: location
  type: text
  config:
    required: false
  label: Location
  default: San Diego
- name: timing
  type: select
  default: Full-time
  config:
    required: false
    options:
    - Full-time
    - Part-time
    - Temp
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Full or part time?
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: standard-page_basic
  hidden: true
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Short job description
  description: Try to keep maximum of ~270 characters
