---
label: Case Studies
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: sub_heading
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Sub heading
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: test_field
  type: text
  config:
    required: false
  label: Test field
  description: Does this do anything
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: standard-page_basic
  hidden: true
